name: Stress Tests

on:
  pull_request:
    types: [labeled]

jobs:
  test:
    if: ${{ github.event.label.name == 'stress test' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run test runner
        run: |
          yarn build
          yarn generate-dynamic-stories
          STRESS_TEST=true yarn test-storybook:ci
